

POST http://localhost:5500/nft/createNft
Content-Type: application/json

{
  "id" : "0x23",
  "name" : "0x23",
  "price" : "0x23",
  "img" : "0x23",
}
###
POST http://localhost:5500/activity/
Content-Type: application/json

{
  "collectionId" : "1",
  "itemName" : "nft12",
  "events" : "buy",
  "price" : 5,
  "from" : "0xsd235",
  "to" : "0xsd444",
  "transactionHash" : "0xdfd"
}
###

GET http://localhost:5500/activity/getAllActivities
Content-Type: application/json


###
GET http://localhost:5500/nft/getNft/:isBuy="false"
Content-Type: application/json


###

PUT http://localhost:5500/api/item/63375e43bd1e4047320b0bab
Content-Type: application/json

{
  "item": "This is the second todo item updated!!"
}

###

DELETE  http://localhost:5500/api/item/633f1980541d802f23394427
Content-Type: application/json
